# Tahap 1 : Import Library Yang Dibutuhkan

In [ ]:
from google_play_scraper import app, reviews, Sort, reviews
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
import csv

# Tahap 2 : Scrapping Data Terhadap Aplikasi PUBG Mobile

In [ ]:
!pip install google_play_scraper

Collecting google_play_scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.9 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google_play_scraper
Successfully installed google_play_scraper-1.2.7

In [ ]:
# Proses scrapping dataset terhadap aplikasi PUBG Mobile yang ada pada playstore dengan menggunakan google_play_scrapper
result, continuation_token = reviews(app_id = "com.tencent.ig",
                 lang = "en",
                 country = "us",
                 sort = Sort.NEWEST,
                 count = 15000)

In [ ]:
# Mengubah scrapping tersebut menjadi datafarame
df_scrapping = pd.DataFrame(result)
df_scrapping.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,06686361-ea85-43b8-b83e-33c388b3eae9,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,bug,5,1,4.3.0,2026-04-10 11:21:38,None,NaT,4.3.0
1,f5dc7048-1007-4bd6-937a-6534e51a858d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,my dad in his ipad is playing with his friends...,5,1,None,2026-04-10 11:16:04,None,NaT,None
2,c9a1e68e-632d-4e24-b7b7-28a6b5993f84,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,good game,5,1,4.3.0,2026-04-10 11:15:36,None,NaT,4.3.0
3,8d3faaf4-0ff0-42f2-9388-13082f652c1a,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,one of the best mobile game ever played in my ...,5,1,4.3.0,2026-04-10 11:13:19,None,NaT,4.3.0
4,54d27e67-f260-422d-8f4e-9b14d1221938,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,My favourite mobile game just so much updates ...,4,1,1.3.0,2026-04-10 11:13:04,None,NaT,1.3.0

# Tahap 3: Melakukan Data Understanding

In [ ]:
# Melihat ukuran dataset
print("Jumlah ulasan:", df_scrapping.shape[0])
print("Jumlah kolom:", df_scrapping.shape[1])

Jumlah ulasan: 15000
Jumlah kolom: 11

In [ ]:
# Melihat jumlah nilai hilang
print("Jumlah nilai hilang adalah: ")
df_scrapping.isna().sum()

Jumlah nilai hilang adalah:

reviewId                    0
userName                    0
userImage                   0
content                     0
score                       0
thumbsUpCount               0
reviewCreatedVersion     3939
at                          0
replyContent            12823
repliedAt               12823
appVersion               3939
dtype: int64

In [ ]:
# Melihat nilai duplikat
print("Jumlah nilai duplikat adalah: ")
df_scrapping.duplicated().sum()

Jumlah nilai duplikat adalah:

np.int64(0)

In [ ]:
# Melihat info umum dataset
print("Info umum dataset:")
df_scrapping.info()

Info umum dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              15000 non-null  object
 1   userName              15000 non-null  object
 2   userImage             15000 non-null  object
 3   content               15000 non-null  object
 4   score                 15000 non-null  int64
 5   thumbsUpCount         15000 non-null  int64
 6   reviewCreatedVersion  11061 non-null  object
 7   at                    15000 non-null  datetime64[ns]
 8   replyContent          2177 non-null   object
 9   repliedAt             2177 non-null   datetime64[ns]
 10  appVersion            11061 non-null  object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 1.3+ MB

# Tahap 4 : Simpan Dataset Tersebut Dengan Format CSV

In [ ]:
# Melakukan seleksi fitur yang relevan
df_scrapping = df_scrapping[['reviewId', 'content', 'score']]

# Menyimpan dataframe dalam format csv
with open('scrapping_pubg.csv', 'w', encoding='utf8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(df_scrapping.columns)

    for row in df_scrapping.itertuples(index=False):
        writer.writerow(row)

In [ ]:
# Melihat kembali dataset yang disimpan untuk memastikan hasil penyimpanan
df_scrapping = pd.read_csv('scrapping_pubg.csv')
df_scrapping.head()

,reviewId,content,score
0,06686361-ea85-43b8-b83e-33c388b3eae9,bug,5
1,f5dc7048-1007-4bd6-937a-6534e51a858d,my dad in his ipad is playing with his friends...,5
2,c9a1e68e-632d-4e24-b7b7-28a6b5993f84,good game,5
3,8d3faaf4-0ff0-42f2-9388-13082f652c1a,one of the best mobile game ever played in my ...,5
4,54d27e67-f260-422d-8f4e-9b14d1221938,My favourite mobile game just so much updates ...,4